import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

const cars = [
  {
    make: 'Nissan',
    model: 'Skyline GT-R',
    year: 1999,
    trim: 'V-Spec',
    engineType: 'RB26DETT Twin-Turbo I6',
    horsepower: 276,
    torque: 293,
    transmission: '6-Speed Manual',
    drivetrain: 'AWD',
    weight: 3153,
    zeroToSixty: 4.9,
    topSpeed: 156,
    msrp: 45000,
    currentValue: 185000,
    imageUrl: 'https://images.unsplash.com/photo-1632245889029-e406faaa34cd?w=800',
    movieAppearances: '2 Fast 2 Furious, Fast & Furious 4',
    famousOwners: "Paul Walker (character Brian O'Conner)",
    productionCount: 11344,
    rarity: 'rare',
    auctionHistory: JSON.stringify([
      { date: '2023-06', house: 'Bring a Trailer', price: 192000, condition: 'Excellent' },
    ]),
  },
  {
    make: 'Toyota',
    model: 'Supra',
    year: 1994,
    trim: 'Turbo',
    engineType: '2JZ-GTE Twin-Turbo I6',
    horsepower: 320,
    torque: 315,
    transmission: '6-Speed Manual',
    drivetrain: 'RWD',
    weight: 3480,
    zeroToSixty: 4.6,
    topSpeed: 155,
    msrp: 40000,
    currentValue: 175000,
    imageUrl: 'https://images.unsplash.com/photo-1626668893632-6f3a4466d22f?w=800',
    movieAppearances: 'The Fast and the Furious (2001)',
    famousOwners: 'Paul Walker',
    productionCount: 11239,
    rarity: 'rare',
  },
  {
    make: 'Mazda',
    model: 'RX-7',
    year: 1993,
    trim: 'Spirit R Type A',
    engineType: '13B-REW Twin-Turbo Rotary',
    horsepower: 276,
    torque: 231,
    transmission: '5-Speed Manual',
    drivetrain: 'RWD',
    weight: 2789,
    zeroToSixty: 5.1,
    topSpeed: 156,
    msrp: 38000,
    currentValue: 95000,
    imageUrl: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800',
    movieAppearances: 'The Fast and the Furious: Tokyo Drift',
    productionCount: 1500,
    rarity: 'rare',
  },
  {
    make: 'Honda',
    model: 'NSX',
    year: 1991,
    trim: 'Type R',
    engineType: 'C30A V6 VTEC',
    horsepower: 270,
    torque: 210,
    transmission: '5-Speed Manual',
    drivetrain: 'RWD',
    weight: 2712,
    zeroToSixty: 5.0,
    topSpeed: 168,
    msrp: 62000,
    currentValue: 225000,
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
    famousOwners: 'Ayrton Senna (development driver)',
    productionCount: 483,
    rarity: 'legendary',
  },
  {
    make: 'Porsche',
    model: '911',
    year: 1973,
    trim: 'Carrera RS 2.7',
    engineType: 'Flat-6',
    horsepower: 210,
    torque: 188,
    transmission: '5-Speed Manual',
    drivetrain: 'RWD',
    weight: 2150,
    zeroToSixty: 5.8,
    topSpeed: 150,
    msrp: 11000,
    currentValue: 1500000,
    imageUrl: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800',
    famousOwners: 'Jerry Seinfeld, Jay Leno',
    productionCount: 1580,
    rarity: 'legendary',
  },
  {
    make: 'Dodge',
    model: 'Charger',
    year: 1970,
    trim: 'R/T',
    engineType: '440 Six Pack V8',
    horsepower: 390,
    torque: 490,
    transmission: '4-Speed Manual',
    drivetrain: 'RWD',
    weight: 3650,
    zeroToSixty: 5.7,
    topSpeed: 150,
    msrp: 3711,
    currentValue: 225000,
    imageUrl: 'https://images.unsplash.com/photo-1612544448445-b8232cff3b6c?w=800',
    movieAppearances: "The Fast and the Furious (Dom's Charger)",
    famousOwners: 'Vin Diesel (character Dominic Toretto)',
    productionCount: 10337,
    rarity: 'rare',
  },
  {
    make: 'Ford',
    model: 'Mustang',
    year: 1967,
    trim: 'Shelby GT500',
    engineType: '428 Police Interceptor V8',
    horsepower: 355,
    torque: 420,
    transmission: '4-Speed Manual',
    drivetrain: 'RWD',
    weight: 3286,
    zeroToSixty: 6.5,
    topSpeed: 130,
    msrp: 4195,
    currentValue: 350000,
    imageUrl: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800',
    movieAppearances: 'Gone in 60 Seconds (Eleanor)',
    productionCount: 2048,
    rarity: 'legendary',
  },
  {
    make: 'Mitsubishi',
    model: 'Lancer Evolution',
    year: 2006,
    trim: 'IX MR',
    engineType: '4G63 Turbo I4',
    horsepower: 286,
    torque: 289,
    transmission: '6-Speed Manual',
    drivetrain: 'AWD',
    weight: 3263,
    zeroToSixty: 4.3,
    topSpeed: 157,
    msrp: 35000,
    currentValue: 65000,
    imageUrl: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800',
    movieAppearances: '2 Fast 2 Furious, The Fast and the Furious: Tokyo Drift',
    productionCount: 2500,
    rarity: 'uncommon',
  },
  {
    make: 'BMW',
    model: 'M3',
    year: 1988,
    trim: 'E30',
    engineType: 'S14 I4',
    horsepower: 195,
    torque: 170,
    transmission: '5-Speed Manual',
    drivetrain: 'RWD',
    weight: 2857,
    zeroToSixty: 6.5,
    topSpeed: 144,
    msrp: 34000,
    currentValue: 125000,
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
    productionCount: 17970,
    rarity: 'rare',
  },
  {
    make: 'DeLorean',
    model: 'DMC-12',
    year: 1981,
    trim: 'Standard',
    engineType: 'PRV V6',
    horsepower: 130,
    torque: 153,
    transmission: '5-Speed Manual',
    drivetrain: 'RWD',
    weight: 2712,
    zeroToSixty: 10.5,
    topSpeed: 109,
    msrp: 25000,
    currentValue: 65000,
    imageUrl: 'https://images.unsplash.com/photo-1609134172728-48f40b2e8c02?w=800',
    movieAppearances: 'Back to the Future Trilogy',
    productionCount: 9000,
    rarity: 'rare',
  },
  {
    make: 'Subaru',
    model: 'Impreza WRX STI',
    year: 2004,
    trim: 'Spec C Type RA',
    engineType: 'EJ257 Turbo Flat-4',
    horsepower: 300,
    torque: 299,
    transmission: '6-Speed Manual',
    drivetrain: 'AWD',
    weight: 3084,
    zeroToSixty: 4.8,
    topSpeed: 155,
    msrp: 32000,
    currentValue: 55000,
    imageUrl: 'https://images.unsplash.com/photo-1626008291472-6de0da84b79f?w=800',
    movieAppearances: 'Baby Driver',
    productionCount: 1000,
    rarity: 'rare',
  },
  {
    make: 'Chevrolet',
    model: 'Camaro',
    year: 1969,
    trim: 'Z/28',
    engineType: '302 V8',
    horsepower: 290,
    torque: 290,
    transmission: '4-Speed Manual',
    drivetrain: 'RWD',
    weight: 3300,
    zeroToSixty: 5.8,
    topSpeed: 130,
    msrp: 3500,
    currentValue: 125000,
    imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
    movieAppearances: 'Transformers (Bumblebee)',
    productionCount: 19014,
    rarity: 'uncommon',
  },
]

const challenges = [
  {
    title: 'Gran Turismo Tribute: $100K Dream Garage',
    description: 'Build your ultimate Gran Turismo garage with a $100,000 budget. Channel that 90s PlayStation energy!',
    theme: 'gran_turismo',
    type: 'budget',
    budgetLimit: 100000,
    difficulty: 'medium',
    points: 150,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    isActive: true,
    startsAt: new Date(),
    endsAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
  },
  {
    title: 'Fast & Furious: Toretto Family Garage',
    description: 'Assemble a garage worthy of Dom and the family. Muscle, imports, and everything in between.',
    theme: 'fast_furious',
    type: 'movie',
    movieReference: 'The Fast and the Furious Franchise',
    difficulty: 'medium',
    points: 200,
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
    isActive: true,
    startsAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
    endsAt: new Date(Date.now() + 48 * 60 * 60 * 1000),
  },
  {
    title: 'Top Gear Challenge: Best Car for $5,000',
    description: 'Channel your inner Clarkson, Hammond, and May. Find the best car under $5,000 and defend your choice!',
    theme: 'top_gear',
    type: 'budget',
    budgetLimit: 5000,
    difficulty: 'hard',
    points: 175,
    imageUrl: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=800',
    isActive: true,
    startsAt: new Date(Date.now() + 48 * 60 * 60 * 1000),
    endsAt: new Date(Date.now() + 72 * 60 * 60 * 1000),
  },
  {
    title: 'Doug Score: Oddballs Only',
    description: 'Find the weirdest, quirkiest cars that would make Doug DeMuro proud. The stranger, the better!',
    theme: 'doug_demuro',
    type: 'oddball',
    difficulty: 'expert',
    points: 250,
    imageUrl: 'https://images.unsplash.com/photo-1609134172728-48f40b2e8c02?w=800',
    isActive: true,
    startsAt: new Date(Date.now() + 72 * 60 * 60 * 1000),
    endsAt: new Date(Date.now() + 96 * 60 * 60 * 1000),
  },
  {
    title: 'Radwood: Peak 80s/90s Aesthetic',
    description: 'Curate a garage that screams rad. Digital dashes, pop-up headlights, and maximum period-correct vibes.',
    theme: 'radwood',
    type: 'era',
    eraStart: 1980,
    eraEnd: 1999,
    difficulty: 'medium',
    points: 175,
    imageUrl: 'https://images.unsplash.com/photo-1621135802920-133df287f89c?w=800',
    isActive: true,
    startsAt: new Date(Date.now() + 96 * 60 * 60 * 1000),
    endsAt: new Date(Date.now() + 120 * 60 * 60 * 1000),
  },
  {
    title: 'Tokyo Drift: JDM Dream Team',
    description: 'Build the ultimate JDM garage. Skylines, Supras, RX-7s, and everything that drifts!',
    theme: 'fast_furious',
    type: 'era',
    eraStart: 1985,
    eraEnd: 2002,
    movieReference: 'The Fast and the Furious: Tokyo Drift',
    difficulty: 'medium',
    points: 200,
    imageUrl: 'https://images.unsplash.com/photo-1632245889029-e406faaa34cd?w=800',
    isActive: true,
    startsAt: new Date(Date.now() + 120 * 60 * 60 * 1000),
    endsAt: new Date(Date.now() + 144 * 60 * 60 * 1000),
  },
]

const unlockableItems = [
  { type: 'garage_theme', name: 'Tokyo Drift Neon', description: 'Neon-soaked garage theme', requirement: 'invites_3', requiredCount: 3, category: 'pop_culture' },
  { type: 'garage_theme', name: "Seinfeld's Collection", description: 'Clean, classic aesthetic', requirement: 'challenge_complete_5', requiredCount: 5, category: 'collector' },
  { type: 'sticker_pack', name: '90s JDM Pack', description: 'Vintage Japanese tuner stickers', requirement: 'invites_1', requiredCount: 1, category: 'pop_culture' },
  { type: 'feature', name: 'Provenance Mode', description: 'Unlock detailed ownership histories', requirement: 'invites_2', requiredCount: 2, category: 'collector' },
  { type: 'badge', name: 'First Challenge', description: 'Completed your first challenge', requirement: 'challenge_complete_1', requiredCount: 1, category: 'both' },
  { type: 'badge', name: 'Social Butterfly', description: 'Invited 5 friends to join', requirement: 'invites_5', requiredCount: 5, category: 'both' },
]

async function main() {
  console.log('🚗 Starting database seed...')

  // Create demo user
  const hashedPassword = await bcrypt.hash('demo123', 12)
  const demoUser = await prisma.user.upsert({
    where: { email: 'demo@carsandconnection.com' },
    update: {},
    create: {
      email: 'demo@carsandconnection.com',
      name: 'Demo User',
      password: hashedPassword,
      points: 500,
      streak: 7,
    },
  })
  console.log('✅ Created demo user')

  // Seed cars
  for (const car of cars) {
    await prisma.car.upsert({
      where: {
        id: `${car.make}-${car.model}-${car.year}`.toLowerCase().replace(/\s/g, '-'),
      },
      update: car,
      create: {
        id: `${car.make}-${car.model}-${car.year}`.toLowerCase().replace(/\s/g, '-'),
        ...car,
      },
    })
  }
  console.log(`✅ Seeded ${cars.length} cars`)

  // Seed challenges
  for (const challenge of challenges) {
    await prisma.challenge.create({
      data: challenge,
    })
  }
  console.log(`✅ Seeded ${challenges.length} challenges`)

  // Seed unlockable items
  for (const item of unlockableItems) {
    await prisma.unlockableItem.create({
      data: item,
    })
  }
  console.log(`✅ Seeded ${unlockableItems.length} unlockable items`)

  console.log('🏁 Database seeding complete!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
